---
abstract: 'parser for Tora language'
author:
  - unknown
build_requires:
  Capture::Tiny: 0
  Devel::PPPort: 0
  ExtUtils::CBuilder: 0
  TAP::Harness: 3.23
  Test::Base: 0
  Test::Differences: 0
  Test::More: 0.98
  Text::MicroTemplate: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: nana
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Nana::Parser:
    file: lib/Nana/Parser.pm
    version: 0.19
  Nana::Translator::Perl:
    file: lib/Nana/Translator/Perl.pm
    version: 0
  Nana::Translator::Perl::Builtins:
    file: lib/Nana/Translator/Perl/Builtins.pm
    version: 0
  Nana::Translator::Perl::Bytes:
    file: lib/Nana/Translator/Perl/Bytes.pm
    version: 0
  Nana::Translator::Perl::Class:
    file: lib/Nana/Translator/Perl/Class.pm
    version: 0
  Nana::Translator::Perl::Code:
    file: lib/Nana/Translator/Perl/Code.pm
    version: 0
  Nana::Translator::Perl::Exception:
    file: lib/Nana/Translator/Perl/Exception.pm
    version: 0
  Nana::Translator::Perl::FilePackage:
    file: lib/Nana/Translator/Perl/FilePackage.pm
    version: 0
  Nana::Translator::Perl::Object:
    file: lib/Nana/Translator/Perl/Object.pm
    version: 0
  Nana::Translator::Perl::PerlObject:
    file: lib/Nana/Translator/Perl/PerlPackage.pm
    version: 0
  Nana::Translator::Perl::PerlPackage:
    file: lib/Nana/Translator/Perl/PerlPackage.pm
    version: 0
  Nana::Translator::Perl::Range:
    file: lib/Nana/Translator/Perl/Range.pm
    version: 0
  Nana::Translator::Perl::Regexp:
    file: lib/Nana/Translator/Perl/Regexp.pm
    version: 0
  Nana::Translator::Perl::RegexpMatched:
    file: lib/Nana/Translator/Perl/RegexpMatched.pm
    version: 0
  Nana::Translator::Perl::Runtime:
    file: lib/Nana/Translator/Perl/Runtime.pm
    version: 0
  Tlack::Runner:
    file: lib/Tlack/Runner.pm
    version: 0
requires:
  Devel::GlobalDestruction: 0.04
  Exporter: 5.58
  File::ShareDir: 1.03
  File::stat: 0
  Getopt::Long::Descriptive: 0
  JSON::XS: 2
  Plack: 0
  Scalar::Util: 0
  Sub::Name: 0
  parent: 0
  perl: 5.012000
resources:
  license: http://dev.perl.org/licenses/
version: 0.19
