/* Generated by re2c 0.13.5 on Thu Apr 26 23:00:15 2012 */
#line 1 "lib/Nana/toke.re"
/* vim: set filetype=cpp: */
#include<stdio.h>
#include<stdlib.h>
#include "token.h"

/**
 * Take a token from string.
 *
 * @args src: source string.
 * @args len: length for 'src'.
 * @args output *used: used chars in src
 * @args output *found_end: make true if found __END__
 * @args output *lineno_inc: incremented line numbers.
 * @return int token id.
 */
int token_op(char *src, size_t len, int *used, int *found_end, int *lineno_inc) {
#define OP(type) do { *used+=(cursor-orig); return type; } while (0)
    *used = skip_ws(src, len, found_end, lineno_inc);
    if (*found_end) {
        return TOKEN_EOF;
    }
    if (*used == len) {
        return TOKEN_EOF;
    }
    char *cursor = src+*used;
    char *orig = cursor;
    char *marker = cursor;

    #line 44 "lib/Nana/toke.re"


    
#line 36 "lib/Nana/toke.c"
	{
		char yych;

		yych = (char)*cursor;
		switch (yych) {
		case '!':	goto yy40;
		case '"':	goto yy64;
		case '$':	goto yy58;
		case '%':	goto yy36;
		case '&':	goto yy50;
		case '\'':	goto yy66;
		case '(':	goto yy30;
		case '*':	goto yy60;
		case '+':	goto yy28;
		case ',':	goto yy38;
		case '-':	goto yy70;
		case '.':	goto yy46;
		case '/':	goto yy34;
		case '0':	goto yy23;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy25;
		case '<':	goto yy32;
		case '=':	goto yy42;
		case '>':	goto yy52;
		case '?':	goto yy26;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'p':
		case 'v':
		case 'y':
		case 'z':	goto yy20;
		case '[':	goto yy68;
		case '\\':	goto yy54;
		case '^':	goto yy44;
		case '_':	goto yy19;
		case 'a':	goto yy13;
		case 'b':	goto yy21;
		case 'c':	goto yy2;
		case 'd':	goto yy7;
		case 'e':	goto yy14;
		case 'f':	goto yy17;
		case 'i':	goto yy6;
		case 'l':	goto yy15;
		case 'm':	goto yy18;
		case 'n':	goto yy9;
		case 'o':	goto yy11;
		case 'q':	goto yy22;
		case 'r':	goto yy4;
		case 's':	goto yy8;
		case 't':	goto yy10;
		case 'u':	goto yy5;
		case 'w':	goto yy16;
		case 'x':	goto yy12;
		case '{':	goto yy62;
		case '|':	goto yy48;
		case '~':	goto yy56;
		default:	goto yy72;
		}
yy2:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case 'l':	goto yy261;
		default:	goto yy155;
		}
yy3:
#line 73 "lib/Nana/toke.re"
		{ OP(TOKEN_IDENT); }
#line 139 "lib/Nana/toke.c"
yy4:
		yych = (char)*++cursor;
		switch (yych) {
		case 'e':	goto yy255;
		default:	goto yy155;
		}
yy5:
		yych = (char)*++cursor;
		switch (yych) {
		case 'n':	goto yy242;
		case 's':	goto yy243;
		default:	goto yy155;
		}
yy6:
		yych = (char)*++cursor;
		switch (yych) {
		case 'f':	goto yy240;
		default:	goto yy155;
		}
yy7:
		yych = (char)*++cursor;
		switch (yych) {
		case 'i':	goto yy235;
		case 'o':	goto yy236;
		default:	goto yy155;
		}
yy8:
		yych = (char)*++cursor;
		switch (yych) {
		case 'e':	goto yy228;
		case 'u':	goto yy229;
		default:	goto yy155;
		}
yy9:
		yych = (char)*++cursor;
		switch (yych) {
		case 'e':	goto yy221;
		case 'o':	goto yy222;
		default:	goto yy155;
		}
yy10:
		yych = (char)*++cursor;
		switch (yych) {
		case 'r':	goto yy215;
		default:	goto yy155;
		}
yy11:
		yych = (char)*++cursor;
		switch (yych) {
		case 'r':	goto yy213;
		default:	goto yy155;
		}
yy12:
		yych = (char)*++cursor;
		switch (yych) {
		case 'o':	goto yy210;
		default:	goto yy155;
		}
yy13:
		yych = (char)*++cursor;
		switch (yych) {
		case 'n':	goto yy207;
		default:	goto yy155;
		}
yy14:
		yych = (char)*++cursor;
		switch (yych) {
		case 'l':	goto yy200;
		default:	goto yy155;
		}
yy15:
		yych = (char)*++cursor;
		switch (yych) {
		case 'a':	goto yy196;
		default:	goto yy155;
		}
yy16:
		yych = (char)*++cursor;
		switch (yych) {
		case 'h':	goto yy191;
		default:	goto yy155;
		}
yy17:
		yych = (char)*++cursor;
		switch (yych) {
		case 'a':	goto yy183;
		case 'o':	goto yy184;
		default:	goto yy155;
		}
yy18:
		yych = (char)*++cursor;
		switch (yych) {
		case 'y':	goto yy181;
		default:	goto yy155;
		}
yy19:
		yych = (char)*++cursor;
		switch (yych) {
		case '_':	goto yy166;
		default:	goto yy155;
		}
yy20:
		yych = (char)*++cursor;
		goto yy155;
yy21:
		yych = (char)*++cursor;
		switch (yych) {
		case '"':	goto yy162;
		case '\'':	goto yy164;
		default:	goto yy155;
		}
yy22:
		yych = (char)*++cursor;
		switch (yych) {
		case '!':
		case '"':
		case '\'':
		case '(':
		case '[':
		case '{':	goto yy149;
		case 'q':	goto yy153;
		case 'r':	goto yy152;
		case 'w':	goto yy151;
		default:	goto yy155;
		}
yy23:
		yych = (char)*(marker = ++cursor);
		switch (yych) {
		case '.':	goto yy141;
		case 'x':	goto yy146;
		default:	goto yy24;
		}
yy24:
#line 74 "lib/Nana/toke.re"
		{ OP(TOKEN_INTEGER); }
#line 275 "lib/Nana/toke.c"
yy25:
		yych = (char)*(marker = ++cursor);
		goto yy140;
yy26:
		++cursor;
#line 76 "lib/Nana/toke.re"
		{ OP(TOKEN_QUESTION); }
#line 283 "lib/Nana/toke.c"
yy28:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '+':	goto yy137;
		case '=':	goto yy135;
		default:	goto yy29;
		}
yy29:
#line 79 "lib/Nana/toke.re"
		{ OP(TOKEN_PLUS);  }
#line 294 "lib/Nana/toke.c"
yy30:
		++cursor;
#line 82 "lib/Nana/toke.re"
		{ OP(TOKEN_LPAREN);  }
#line 299 "lib/Nana/toke.c"
yy32:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '<':	goto yy127;
		case '=':	goto yy125;
		default:	goto yy33;
		}
yy33:
#line 113 "lib/Nana/toke.re"
		{ OP(TOKEN_GT); }
#line 310 "lib/Nana/toke.c"
yy34:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy123;
		default:	goto yy35;
		}
yy35:
#line 85 "lib/Nana/toke.re"
		{ OP(TOKEN_DIV); }
#line 320 "lib/Nana/toke.c"
yy36:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy121;
		default:	goto yy37;
		}
yy37:
#line 87 "lib/Nana/toke.re"
		{ OP(TOKEN_MOD); }
#line 330 "lib/Nana/toke.c"
yy38:
		++cursor;
#line 88 "lib/Nana/toke.re"
		{ OP(TOKEN_COMMA); }
#line 335 "lib/Nana/toke.c"
yy40:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy119;
		case '~':	goto yy117;
		default:	goto yy41;
		}
yy41:
#line 91 "lib/Nana/toke.re"
		{ OP(TOKEN_NOT); }
#line 346 "lib/Nana/toke.c"
yy42:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy115;
		case '>':	goto yy113;
		case '~':	goto yy111;
		default:	goto yy43;
		}
yy43:
#line 95 "lib/Nana/toke.re"
		{ OP(TOKEN_ASSIGN); }
#line 358 "lib/Nana/toke.c"
yy44:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy109;
		default:	goto yy45;
		}
yy45:
#line 97 "lib/Nana/toke.re"
		{ OP(TOKEN_XOR); }
#line 368 "lib/Nana/toke.c"
yy46:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '.':	goto yy105;
		default:	goto yy47;
		}
yy47:
#line 100 "lib/Nana/toke.re"
		{ OP(TOKEN_DOT); }
#line 378 "lib/Nana/toke.c"
yy48:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy99;
		case '|':	goto yy101;
		default:	goto yy49;
		}
yy49:
#line 104 "lib/Nana/toke.re"
		{ OP(TOKEN_OR); }
#line 389 "lib/Nana/toke.c"
yy50:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '&':	goto yy97;
		case '=':	goto yy95;
		default:	goto yy51;
		}
yy51:
#line 107 "lib/Nana/toke.re"
		{ OP(TOKEN_AND); }
#line 400 "lib/Nana/toke.c"
yy52:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy89;
		case '>':	goto yy91;
		default:	goto yy53;
		}
yy53:
#line 117 "lib/Nana/toke.re"
		{ OP(TOKEN_LT); }
#line 411 "lib/Nana/toke.c"
yy54:
		++cursor;
#line 118 "lib/Nana/toke.re"
		{ OP(TOKEN_REF); }
#line 416 "lib/Nana/toke.c"
yy56:
		++cursor;
#line 119 "lib/Nana/toke.re"
		{ OP(TOKEN_TILDE); }
#line 421 "lib/Nana/toke.c"
yy58:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '{':	goto yy87;
		default:	goto yy59;
		}
yy59:
#line 144 "lib/Nana/toke.re"
		{ return TOKEN_EOF; }
#line 431 "lib/Nana/toke.c"
yy60:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '*':	goto yy83;
		case '=':	goto yy81;
		default:	goto yy61;
		}
yy61:
#line 124 "lib/Nana/toke.re"
		{ OP(TOKEN_MUL); }
#line 442 "lib/Nana/toke.c"
yy62:
		++cursor;
#line 128 "lib/Nana/toke.re"
		{ OP(TOKEN_LBRACE); }
#line 447 "lib/Nana/toke.c"
yy64:
		++cursor;
#line 136 "lib/Nana/toke.re"
		{ OP(TOKEN_STRING_DQ); }
#line 452 "lib/Nana/toke.c"
yy66:
		++cursor;
#line 137 "lib/Nana/toke.re"
		{ OP(TOKEN_STRING_SQ); }
#line 457 "lib/Nana/toke.c"
yy68:
		++cursor;
#line 138 "lib/Nana/toke.re"
		{ OP(TOKEN_LBRACKET); }
#line 462 "lib/Nana/toke.c"
yy70:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '-':	goto yy77;
		case '=':	goto yy73;
		case '>':	goto yy75;
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy79;
		default:	goto yy71;
		}
yy71:
#line 143 "lib/Nana/toke.re"
		{ OP(TOKEN_MINUS); }
#line 500 "lib/Nana/toke.c"
yy72:
		yych = (char)*++cursor;
		goto yy59;
yy73:
		++cursor;
#line 142 "lib/Nana/toke.re"
		{ OP(TOKEN_MINUS_ASSIGN); }
#line 508 "lib/Nana/toke.c"
yy75:
		++cursor;
#line 141 "lib/Nana/toke.re"
		{ OP(TOKEN_LAMBDA); }
#line 513 "lib/Nana/toke.c"
yy77:
		++cursor;
#line 140 "lib/Nana/toke.re"
		{ OP(TOKEN_MINUSMINUS); }
#line 518 "lib/Nana/toke.c"
yy79:
		++cursor;
#line 139 "lib/Nana/toke.re"
		{ OP(TOKEN_FILETEST); }
#line 523 "lib/Nana/toke.c"
yy81:
		++cursor;
#line 123 "lib/Nana/toke.re"
		{ OP(TOKEN_MUL_ASSIGN); }
#line 528 "lib/Nana/toke.c"
yy83:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy85;
		default:	goto yy84;
		}
yy84:
#line 122 "lib/Nana/toke.re"
		{ OP(TOKEN_POW); }
#line 538 "lib/Nana/toke.c"
yy85:
		++cursor;
#line 121 "lib/Nana/toke.re"
		{ OP(TOKEN_POW_ASSIGN); }
#line 543 "lib/Nana/toke.c"
yy87:
		++cursor;
#line 120 "lib/Nana/toke.re"
		{ OP(TOKEN_DEREF); }
#line 548 "lib/Nana/toke.c"
yy89:
		++cursor;
#line 116 "lib/Nana/toke.re"
		{ OP(TOKEN_LE); }
#line 553 "lib/Nana/toke.c"
yy91:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy93;
		default:	goto yy92;
		}
yy92:
#line 115 "lib/Nana/toke.re"
		{ OP(TOKEN_RSHIFT); }
#line 563 "lib/Nana/toke.c"
yy93:
		++cursor;
#line 114 "lib/Nana/toke.re"
		{ OP(TOKEN_RSHIFT_ASSIGN); }
#line 568 "lib/Nana/toke.c"
yy95:
		++cursor;
#line 106 "lib/Nana/toke.re"
		{ OP(TOKEN_AND_ASSIGN); }
#line 573 "lib/Nana/toke.c"
yy97:
		++cursor;
#line 105 "lib/Nana/toke.re"
		{ OP(TOKEN_ANDAND); }
#line 578 "lib/Nana/toke.c"
yy99:
		++cursor;
#line 103 "lib/Nana/toke.re"
		{ OP(TOKEN_OR_ASSIGN); }
#line 583 "lib/Nana/toke.c"
yy101:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy103;
		default:	goto yy102;
		}
yy102:
#line 102 "lib/Nana/toke.re"
		{ OP(TOKEN_OROR); }
#line 593 "lib/Nana/toke.c"
yy103:
		++cursor;
#line 101 "lib/Nana/toke.re"
		{ OP(TOKEN_OROR_ASSIGN); }
#line 598 "lib/Nana/toke.c"
yy105:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '.':	goto yy107;
		default:	goto yy106;
		}
yy106:
#line 99 "lib/Nana/toke.re"
		{ OP(TOKEN_DOTDOT); }
#line 608 "lib/Nana/toke.c"
yy107:
		++cursor;
#line 98 "lib/Nana/toke.re"
		{ OP(TOKEN_DOTDOTDOT); }
#line 613 "lib/Nana/toke.c"
yy109:
		++cursor;
#line 96 "lib/Nana/toke.re"
		{ OP(TOKEN_XOR_ASSIGN); }
#line 618 "lib/Nana/toke.c"
yy111:
		++cursor;
#line 94 "lib/Nana/toke.re"
		{ OP(TOKEN_REGEXP_MATCH); }
#line 623 "lib/Nana/toke.c"
yy113:
		++cursor;
#line 93 "lib/Nana/toke.re"
		{ OP(TOKEN_FAT_COMMA); }
#line 628 "lib/Nana/toke.c"
yy115:
		++cursor;
#line 92 "lib/Nana/toke.re"
		{ OP(TOKEN_EQUAL_EQUAL); }
#line 633 "lib/Nana/toke.c"
yy117:
		++cursor;
#line 90 "lib/Nana/toke.re"
		{ OP(TOKEN_REGEXP_NOT_MATCH); }
#line 638 "lib/Nana/toke.c"
yy119:
		++cursor;
#line 89 "lib/Nana/toke.re"
		{ OP(TOKEN_NOT_EQUAL); }
#line 643 "lib/Nana/toke.c"
yy121:
		++cursor;
#line 86 "lib/Nana/toke.re"
		{ OP(TOKEN_MOD_ASSIGN); }
#line 648 "lib/Nana/toke.c"
yy123:
		++cursor;
#line 84 "lib/Nana/toke.re"
		{ OP(TOKEN_DIV_ASSIGN); }
#line 653 "lib/Nana/toke.c"
yy125:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '>':	goto yy133;
		default:	goto yy126;
		}
yy126:
#line 112 "lib/Nana/toke.re"
		{ OP(TOKEN_GE); }
#line 663 "lib/Nana/toke.c"
yy127:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '\'':	goto yy129;
		case '=':	goto yy131;
		default:	goto yy128;
		}
yy128:
#line 110 "lib/Nana/toke.re"
		{ OP(TOKEN_LSHIFT); }
#line 674 "lib/Nana/toke.c"
yy129:
		++cursor;
#line 83 "lib/Nana/toke.re"
		{ OP(TOKEN_HEREDOC_SQ_START);  }
#line 679 "lib/Nana/toke.c"
yy131:
		++cursor;
#line 108 "lib/Nana/toke.re"
		{ OP(TOKEN_LSHIFT_ASSIGN); }
#line 684 "lib/Nana/toke.c"
yy133:
		++cursor;
#line 111 "lib/Nana/toke.re"
		{ OP(TOKEN_CMP); }
#line 689 "lib/Nana/toke.c"
yy135:
		++cursor;
#line 78 "lib/Nana/toke.re"
		{ OP(TOKEN_PLUS_ASSIGN);  }
#line 694 "lib/Nana/toke.c"
yy137:
		++cursor;
#line 77 "lib/Nana/toke.re"
		{ OP(TOKEN_PLUSPLUS); }
#line 699 "lib/Nana/toke.c"
yy139:
		marker = ++cursor;
		yych = (char)*cursor;
yy140:
		switch (yych) {
		case '.':	goto yy141;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy139;
		default:	goto yy24;
		}
yy141:
		yych = (char)*++cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy143;
		default:	goto yy142;
		}
yy142:
		cursor = marker;
		goto yy24;
yy143:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy143;
		default:	goto yy145;
		}
yy145:
#line 75 "lib/Nana/toke.re"
		{ OP(TOKEN_DOUBLE); }
#line 755 "lib/Nana/toke.c"
yy146:
		yych = (char)*++cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':	goto yy147;
		default:	goto yy142;
		}
yy147:
		++cursor;
		yych = (char)*cursor;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':	goto yy147;
		default:	goto yy24;
		}
yy149:
		++cursor;
#line 135 "lib/Nana/toke.re"
		{ OP(TOKEN_STRING_Q_START); }
#line 815 "lib/Nana/toke.c"
yy151:
		yych = (char)*++cursor;
		switch (yych) {
		case '!':
		case '"':
		case '\'':
		case '(':
		case '[':
		case '{':	goto yy160;
		default:	goto yy155;
		}
yy152:
		yych = (char)*++cursor;
		switch (yych) {
		case '!':
		case '"':
		case '\'':
		case '(':
		case '[':
		case '{':	goto yy158;
		default:	goto yy155;
		}
yy153:
		yych = (char)*++cursor;
		switch (yych) {
		case '!':
		case '"':
		case '\'':
		case '(':
		case '[':
		case '{':	goto yy156;
		default:	goto yy155;
		}
yy154:
		++cursor;
		yych = (char)*cursor;
yy155:
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy3;
		}
yy156:
		++cursor;
#line 132 "lib/Nana/toke.re"
		{ OP(TOKEN_STRING_QQ_START); }
#line 923 "lib/Nana/toke.c"
yy158:
		++cursor;
#line 133 "lib/Nana/toke.re"
		{ OP(TOKEN_REGEXP_QR_START); }
#line 928 "lib/Nana/toke.c"
yy160:
		++cursor;
#line 134 "lib/Nana/toke.re"
		{ OP(TOKEN_QW_START); }
#line 933 "lib/Nana/toke.c"
yy162:
		++cursor;
#line 80 "lib/Nana/toke.re"
		{ OP(TOKEN_BYTES_DQ);  }
#line 938 "lib/Nana/toke.c"
yy164:
		++cursor;
#line 81 "lib/Nana/toke.re"
		{ OP(TOKEN_BYTES_SQ);  }
#line 943 "lib/Nana/toke.c"
yy166:
		yych = (char)*++cursor;
		switch (yych) {
		case 'F':	goto yy167;
		case 'L':	goto yy168;
		default:	goto yy155;
		}
yy167:
		yych = (char)*++cursor;
		switch (yych) {
		case 'I':	goto yy175;
		default:	goto yy155;
		}
yy168:
		yych = (char)*++cursor;
		switch (yych) {
		case 'I':	goto yy169;
		default:	goto yy155;
		}
yy169:
		yych = (char)*++cursor;
		switch (yych) {
		case 'N':	goto yy170;
		default:	goto yy155;
		}
yy170:
		yych = (char)*++cursor;
		switch (yych) {
		case 'E':	goto yy171;
		default:	goto yy155;
		}
yy171:
		yych = (char)*++cursor;
		switch (yych) {
		case '_':	goto yy172;
		default:	goto yy155;
		}
yy172:
		yych = (char)*++cursor;
		switch (yych) {
		case '_':	goto yy173;
		default:	goto yy155;
		}
yy173:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy174;
		}
yy174:
#line 72 "lib/Nana/toke.re"
		{ OP(TOKEN_LINE); }
#line 1058 "lib/Nana/toke.c"
yy175:
		yych = (char)*++cursor;
		switch (yych) {
		case 'L':	goto yy176;
		default:	goto yy155;
		}
yy176:
		yych = (char)*++cursor;
		switch (yych) {
		case 'E':	goto yy177;
		default:	goto yy155;
		}
yy177:
		yych = (char)*++cursor;
		switch (yych) {
		case '_':	goto yy178;
		default:	goto yy155;
		}
yy178:
		yych = (char)*++cursor;
		switch (yych) {
		case '_':	goto yy179;
		default:	goto yy155;
		}
yy179:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy180;
		}
yy180:
#line 71 "lib/Nana/toke.re"
		{ OP(TOKEN_FILE); }
#line 1154 "lib/Nana/toke.c"
yy181:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy182;
		}
yy182:
#line 66 "lib/Nana/toke.re"
		{ OP(TOKEN_MY); }
#line 1226 "lib/Nana/toke.c"
yy183:
		yych = (char)*++cursor;
		switch (yych) {
		case 'l':	goto yy187;
		default:	goto yy155;
		}
yy184:
		yych = (char)*++cursor;
		switch (yych) {
		case 'r':	goto yy185;
		default:	goto yy155;
		}
yy185:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy186;
		}
yy186:
#line 65 "lib/Nana/toke.re"
		{ OP(TOKEN_FOR); }
#line 1310 "lib/Nana/toke.c"
yy187:
		yych = (char)*++cursor;
		switch (yych) {
		case 's':	goto yy188;
		default:	goto yy155;
		}
yy188:
		yych = (char)*++cursor;
		switch (yych) {
		case 'e':	goto yy189;
		default:	goto yy155;
		}
yy189:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy190;
		}
yy190:
#line 69 "lib/Nana/toke.re"
		{ OP(TOKEN_FALSE); }
#line 1394 "lib/Nana/toke.c"
yy191:
		yych = (char)*++cursor;
		switch (yych) {
		case 'i':	goto yy192;
		default:	goto yy155;
		}
yy192:
		yych = (char)*++cursor;
		switch (yych) {
		case 'l':	goto yy193;
		default:	goto yy155;
		}
yy193:
		yych = (char)*++cursor;
		switch (yych) {
		case 'e':	goto yy194;
		default:	goto yy155;
		}
yy194:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy195;
		}
yy195:
#line 64 "lib/Nana/toke.re"
		{ OP(TOKEN_WHILE); }
#line 1484 "lib/Nana/toke.c"
yy196:
		yych = (char)*++cursor;
		switch (yych) {
		case 's':	goto yy197;
		default:	goto yy155;
		}
yy197:
		yych = (char)*++cursor;
		switch (yych) {
		case 't':	goto yy198;
		default:	goto yy155;
		}
yy198:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy199;
		}
yy199:
#line 61 "lib/Nana/toke.re"
		{ OP(TOKEN_LAST); }
#line 1568 "lib/Nana/toke.c"
yy200:
		yych = (char)*++cursor;
		switch (yych) {
		case 's':	goto yy201;
		default:	goto yy155;
		}
yy201:
		yych = (char)*++cursor;
		switch (yych) {
		case 'e':	goto yy202;
		case 'i':	goto yy204;
		default:	goto yy155;
		}
yy202:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy203;
		}
yy203:
#line 63 "lib/Nana/toke.re"
		{ OP(TOKEN_ELSE); }
#line 1653 "lib/Nana/toke.c"
yy204:
		yych = (char)*++cursor;
		switch (yych) {
		case 'f':	goto yy205;
		default:	goto yy155;
		}
yy205:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy206;
		}
yy206:
#line 60 "lib/Nana/toke.re"
		{ OP(TOKEN_ELSIF); }
#line 1731 "lib/Nana/toke.c"
yy207:
		yych = (char)*++cursor;
		switch (yych) {
		case 'd':	goto yy208;
		default:	goto yy155;
		}
yy208:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy209;
		}
yy209:
#line 59 "lib/Nana/toke.re"
		{ OP(TOKEN_STR_AND); }
#line 1809 "lib/Nana/toke.c"
yy210:
		yych = (char)*++cursor;
		switch (yych) {
		case 'r':	goto yy211;
		default:	goto yy155;
		}
yy211:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy212;
		}
yy212:
#line 58 "lib/Nana/toke.re"
		{ OP(TOKEN_STR_XOR); }
#line 1887 "lib/Nana/toke.c"
yy213:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy214;
		}
yy214:
#line 57 "lib/Nana/toke.re"
		{ OP(TOKEN_STR_OR); }
#line 1959 "lib/Nana/toke.c"
yy215:
		yych = (char)*++cursor;
		switch (yych) {
		case 'u':	goto yy218;
		case 'y':	goto yy216;
		default:	goto yy155;
		}
yy216:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy217;
		}
yy217:
#line 56 "lib/Nana/toke.re"
		{ OP(TOKEN_TRY); }
#line 2038 "lib/Nana/toke.c"
yy218:
		yych = (char)*++cursor;
		switch (yych) {
		case 'e':	goto yy219;
		default:	goto yy155;
		}
yy219:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy220;
		}
yy220:
#line 68 "lib/Nana/toke.re"
		{ OP(TOKEN_TRUE); }
#line 2116 "lib/Nana/toke.c"
yy221:
		yych = (char)*++cursor;
		switch (yych) {
		case 'x':	goto yy225;
		default:	goto yy155;
		}
yy222:
		yych = (char)*++cursor;
		switch (yych) {
		case 't':	goto yy223;
		default:	goto yy155;
		}
yy223:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy224;
		}
yy224:
#line 54 "lib/Nana/toke.re"
		{ OP(TOKEN_STR_NOT); }
#line 2200 "lib/Nana/toke.c"
yy225:
		yych = (char)*++cursor;
		switch (yych) {
		case 't':	goto yy226;
		default:	goto yy155;
		}
yy226:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy227;
		}
yy227:
#line 62 "lib/Nana/toke.re"
		{ OP(TOKEN_NEXT); }
#line 2278 "lib/Nana/toke.c"
yy228:
		yych = (char)*++cursor;
		switch (yych) {
		case 'l':	goto yy232;
		default:	goto yy155;
		}
yy229:
		yych = (char)*++cursor;
		switch (yych) {
		case 'b':	goto yy230;
		default:	goto yy155;
		}
yy230:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy231;
		}
yy231:
#line 53 "lib/Nana/toke.re"
		{ OP(TOKEN_SUB); }
#line 2362 "lib/Nana/toke.c"
yy232:
		yych = (char)*++cursor;
		switch (yych) {
		case 'f':	goto yy233;
		default:	goto yy155;
		}
yy233:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy234;
		}
yy234:
#line 70 "lib/Nana/toke.re"
		{ OP(TOKEN_SELF); }
#line 2440 "lib/Nana/toke.c"
yy235:
		yych = (char)*++cursor;
		switch (yych) {
		case 'e':	goto yy238;
		default:	goto yy155;
		}
yy236:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy237;
		}
yy237:
#line 52 "lib/Nana/toke.re"
		{ OP(TOKEN_DO); }
#line 2518 "lib/Nana/toke.c"
yy238:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy239;
		}
yy239:
#line 55 "lib/Nana/toke.re"
		{ OP(TOKEN_DIE); }
#line 2590 "lib/Nana/toke.c"
yy240:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy241;
		}
yy241:
#line 51 "lib/Nana/toke.re"
		{ OP(TOKEN_IF); }
#line 2662 "lib/Nana/toke.c"
yy242:
		yych = (char)*++cursor;
		switch (yych) {
		case 'd':	goto yy247;
		case 'l':	goto yy246;
		default:	goto yy155;
		}
yy243:
		yych = (char)*++cursor;
		switch (yych) {
		case 'e':	goto yy244;
		default:	goto yy155;
		}
yy244:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy245;
		}
yy245:
#line 49 "lib/Nana/toke.re"
		{ OP(TOKEN_USE); }
#line 2747 "lib/Nana/toke.c"
yy246:
		yych = (char)*++cursor;
		switch (yych) {
		case 'e':	goto yy251;
		default:	goto yy155;
		}
yy247:
		yych = (char)*++cursor;
		switch (yych) {
		case 'e':	goto yy248;
		default:	goto yy155;
		}
yy248:
		yych = (char)*++cursor;
		switch (yych) {
		case 'f':	goto yy249;
		default:	goto yy155;
		}
yy249:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy250;
		}
yy250:
#line 67 "lib/Nana/toke.re"
		{ OP(TOKEN_UNDEF); }
#line 2837 "lib/Nana/toke.c"
yy251:
		yych = (char)*++cursor;
		switch (yych) {
		case 's':	goto yy252;
		default:	goto yy155;
		}
yy252:
		yych = (char)*++cursor;
		switch (yych) {
		case 's':	goto yy253;
		default:	goto yy155;
		}
yy253:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy254;
		}
yy254:
#line 50 "lib/Nana/toke.re"
		{ OP(TOKEN_UNLESS); }
#line 2921 "lib/Nana/toke.c"
yy255:
		yych = (char)*++cursor;
		switch (yych) {
		case 't':	goto yy256;
		default:	goto yy155;
		}
yy256:
		yych = (char)*++cursor;
		switch (yych) {
		case 'u':	goto yy257;
		default:	goto yy155;
		}
yy257:
		yych = (char)*++cursor;
		switch (yych) {
		case 'r':	goto yy258;
		default:	goto yy155;
		}
yy258:
		yych = (char)*++cursor;
		switch (yych) {
		case 'n':	goto yy259;
		default:	goto yy155;
		}
yy259:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy260;
		}
yy260:
#line 48 "lib/Nana/toke.re"
		{ OP(TOKEN_RETURN); }
#line 3017 "lib/Nana/toke.c"
yy261:
		yych = (char)*++cursor;
		switch (yych) {
		case 'a':	goto yy262;
		default:	goto yy155;
		}
yy262:
		yych = (char)*++cursor;
		switch (yych) {
		case 's':	goto yy263;
		default:	goto yy155;
		}
yy263:
		yych = (char)*++cursor;
		switch (yych) {
		case 's':	goto yy264;
		default:	goto yy155;
		}
yy264:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy265;
		}
yy265:
#line 47 "lib/Nana/toke.re"
		{ OP(TOKEN_CLASS);  }
#line 3107 "lib/Nana/toke.c"
	}
#line 146 "lib/Nana/toke.re"

    abort(); /* should not reach here */
}
